### ISSUE TITLE
cmake or build script?

### ISSUE THREAD

**Issue by SpudGunMan** [bobh/ILooper#1]
saw your thing in QRZ but this project is lacking a lot of help to build - I dont want to download your 2GB OS can you provide the binary files as your code seems to have issues compiling 

any chance you can cmake or build script for dependency checking (I have port audio and wirepi installed and still no luck with a compile)

sudo cc LoopRecord.c
In file included from LoopRecord.c:69:0:
commonTypes.h:47:0: warning: "TRUE" redefined
 #define TRUE (1)
 ^
In file included from LoopRecord.c:67:0:
/usr/local/include/wiringPi.h:31:0: note: this is the location of the previous definition
 #  define TRUE (1==1)
 ^
In file included from LoopRecord.c:69:0:
commonTypes.h:48:0: warning: "FALSE" redefined
 #define FALSE (0)
 ^
In file included from LoopRecord.c:67:0:
/usr/local/include/wiringPi.h:32:0: note: this is the location of the previous definition
 #  define FALSE (!TRUE)
 ^
/tmp/ccVkWzoZ.o: In function `toggleGreenLED':
LoopRecord.c:(.text+0x2c): undefined reference to`digitalWrite'
LoopRecord.c:(.text+0x48): undefined reference to `digitalWrite'
/tmp/ccVkWzoZ.o: In function`fatalError':
LoopRecord.c:(.text+0x70): undefined reference to `delay'
/tmp/ccVkWzoZ.o: In function`checkButton':
LoopRecord.c:(.text+0xf0): undefined reference to `digitalRead'
LoopRecord.c:(.text+0x110): undefined reference to`Pa_Sleep'
LoopRecord.c:(.text+0x118): undefined reference to `digitalRead'
LoopRecord.c:(.text+0x138): undefined reference to`Pa_Sleep'
LoopRecord.c:(.text+0x140): undefined reference to `digitalRead'
/tmp/ccVkWzoZ.o: In function`doState':
LoopRecord.c:(.text+0x1f4): undefined reference to `digitalWrite'
LoopRecord.c:(.text+0x2c8): undefined reference to`digitalWrite'
LoopRecord.c:(.text+0x310): undefined reference to `digitalRead'
LoopRecord.c:(.text+0x340): undefined reference to`playback'
LoopRecord.c:(.text+0x394): undefined reference to `playback'
LoopRecord.c:(.text+0x49c): undefined reference to`playback'
LoopRecord.c:(.text+0x4b4): undefined reference to `digitalWrite'
LoopRecord.c:(.text+0x4d8): undefined reference to`digitalRead'
/tmp/ccVkWzoZ.o: In function `main':
LoopRecord.c:(.text+0x640): undefined reference to`Pa_Initialize'
LoopRecord.c:(.text+0x664): undefined reference to `Pa_GetDefaultInputDevice'
LoopRecord.c:(.text+0x6c4): undefined reference to`Pa_GetDeviceInfo'
LoopRecord.c:(.text+0x710): undefined reference to `Pa_OpenStream'
LoopRecord.c:(.text+0x740): undefined reference to`Pa_IsFormatSupported'
LoopRecord.c:(.text+0x764): undefined reference to `wiringPiSetup'
LoopRecord.c:(.text+0x7b4): undefined reference to`pinMode'
LoopRecord.c:(.text+0x7c0): undefined reference to `digitalWrite'
LoopRecord.c:(.text+0x7cc): undefined reference to`pinMode'
LoopRecord.c:(.text+0x7d8): undefined reference to `pullUpDnControl'
LoopRecord.c:(.text+0x7e4): undefined reference to`pinMode'
LoopRecord.c:(.text+0x7f0): undefined reference to `pullUpDnControl'
LoopRecord.c:(.text+0x7fc): undefined reference to`pinMode'
LoopRecord.c:(.text+0x808): undefined reference to `pullUpDnControl'
LoopRecord.c:(.text+0x818): undefined reference to`Pa_StartStream'
LoopRecord.c:(.text+0x858): undefined reference to `Pa_Sleep'
LoopRecord.c:(.text+0x870): undefined reference to`Pa_Sleep'
LoopRecord.c:(.text+0x8a4): undefined reference to `Pa_IsStreamActive'
LoopRecord.c:(.text+0x8e4): undefined reference to`Pa_CloseStream'
LoopRecord.c:(.text+0x90c): undefined reference to `digitalRead'
LoopRecord.c:(.text+0xaa0): undefined reference to`Pa_Sleep'
LoopRecord.c:(.text+0xaec): undefined reference to `recordCallback'
LoopRecord.c:(.text+0xb34): undefined reference to`Pa_Terminate'
LoopRecord.c:(.text+0xbb4): undefined reference to `Pa_GetErrorText'
collect2: error: ld returned 1 exit status

sudo find / -name "portaudio.h"
/usr/include/portaudio.h

**Comment by SpudGunMan** [comment]
This was closed but not resolved?

**Comment by bobh** [comment]
I don't use a make file. I use gcc on the command line. Just list the files on the command line, the libraries and the math option. 
You should read up on gcc.

**Comment by bobh** [comment]
You're going to need to compile portaudio for your processor and link that library. Look at this: [http://portaudio.com/docs/v19-doxydocs/compile_linux.html](url)
Compile the library and the test files. Then substitute my files. But there is all kinds of configuration to do to get the USB to work. Use the binary image.
